### ISSUE TITLE
2 small issues

### ISSUE THREAD

**Issue by jeroenweustink** [ifedapoolarewaju/django-userplus#1]
I saw django-userplus on django packages and it came exactly at the right moment because i'm currently working on my user management.

I ran into 2 small issues:

**Activation expiry date**
`django.db.utils.IntegrityError: (1048, "Column 'activation_expiry_date' cannot be null")`

I fixed this by adding a pre_save signal to my user model. Like this
`@receiver(pre_save, sender=User, dispatch_uid="add_activation_expiry_date")
def add_activation_expiry_date(sender, instance, **kwargs):
    instance.activation_expiry_date = timezone.now() + timedelta(days=1)` 

Maybe a default value that can be set in a setting parameter?

**Documentation about AUTH_USER_MODEL**
As you probably know you need to define a custom user model when not using the django default. However this is not documented in the README of this repo.

Keep up the good work, loving this package so far.

**Comment by ifedapoolarewaju** [comment]
@jeroenweustink Thank you for the feedback! 😃 Currently working on fixing those ....should be done soon!

**Comment by ifedapoolarewaju** [comment]
fixed in [v0.3](https://github.com/ifedapoolarewaju/django-userplus/tree/v0.3)
